In [2]:
import seaborn as sns
df=sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
X=df[['tip','sex','smoker','day','time','size']]
Y=df["total_bill"]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=10)
X_train

      tip     sex smoker   day    time  size
58   1.76    Male    Yes   Sat  Dinner     2
1    1.66    Male     No   Sun  Dinner     3
2    3.50    Male     No   Sun  Dinner     3
68   2.01    Male     No   Sat  Dinner     2
184  3.00    Male    Yes   Sun  Dinner     2
..    ...     ...    ...   ...     ...   ...
64   2.64    Male     No   Sat  Dinner     3
15   3.92    Male     No   Sun  Dinner     2
228  2.72    Male     No   Sat  Dinner     2
125  4.20  Female     No  Thur   Lunch     6
9    3.23    Male     No   Sun  Dinner     2

[183 rows x 6 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
l2=LabelEncoder()
l3=LabelEncoder()
X_train['sex']=l1.fit_transform(X_train['sex'])
X_train['smoker']=l2.fit_transform(X_train['smoker'])
X_train['time']=l3.fit_transform(X_train['time'])
X_test['sex']=l1.transform(X_test['sex'])
X_test['smoker']=l2.transform(X_test['smoker'])
X_test['time']=l3.transform(X_test['time'])

In [6]:
X_train

      tip  sex  smoker   day  time  size
58   1.76    1       1   Sat     0     2
1    1.66    1       0   Sun     0     3
2    3.50    1       0   Sun     0     3
68   2.01    1       0   Sat     0     2
184  3.00    1       1   Sun     0     2
..    ...  ...     ...   ...   ...   ...
64   2.64    1       0   Sat     0     3
15   3.92    1       0   Sun     0     2
228  2.72    1       0   Sat     0     2
125  4.20    0       0  Thur     1     6
9    3.23    1       0   Sun     0     2

[183 rows x 6 columns]

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')
X_train=ct.fit_transform(X_train)
X_test=ct.transform(X_test)
X_train

array([[1., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 0., 0., 3.],
       [0., 1., 0., ..., 0., 0., 3.],
       ...,
       [1., 0., 0., ..., 0., 0., 2.],
       [0., 0., 1., ..., 0., 1., 6.],
       [0., 1., 0., ..., 0., 0., 2.]], shape=(183, 8))

In [8]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score
svr=SVR()
svr.fit(X_train,Y_train)
y_pred=svr.predict(X_test)
print(r2_score(Y_test,y_pred))

0.46028114561159283

In [9]:
params=[{
    'C':[0.1,1,10,100,1000],
    'gamma':[0.001,0.01,0.1,10,100],
    'kernel':['rbf']
},
{
    'C':[0.1,1,10,100,1000],
    'gamma':[0.001,0.01,0.1,10,100],
    'kernel':['linear']
},
{
    'C':[0.1],
    'gamma':[0.001,0.01,0.1,10],
    'kernel':['poly']
}]

In [11]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(SVR(),param_grid=params,cv=5,verbose=3,refit=True)
grid.fit(X_train,Y_train)
grid.best_params_

Fitting 5 folds for each of 54 candidates, totalling 270 fits
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.080 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.068 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.167 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.006 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.105 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.053 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.028 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.108 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.040 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.058 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.013 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.021 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.010 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.124 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.050 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=10, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=10, kernel=rbf;, score=-0.072 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=10, kernel=rbf;, score=-0.167 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=10, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=10, kernel=rbf;, score=-0.109 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=100, kernel=rbf;, score=-0.085 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=100, kernel=rbf;, score=-0.074 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=100, kernel=rbf;, score=-0.171 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=100, kernel=rbf;, score=-0.007 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=100, kernel=rbf;, score=-0.108 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.014 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.096 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.050 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.051 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.121 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.221 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.269 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.305 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.252 total time=   0.0s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.189 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.254 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.533 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.347 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.503 total time=   0.0s
[CV 1/5] END ........C=1, gamma=10, kernel=rbf;, score=-0.043 total time=   0.0s
[CV 2/5] END ........C=1, gamma=10, kernel=rbf;, score=-0.046 total time=   0.0s
[CV 3/5] END ........C=1, gamma=10, kernel=rbf;, score=-0.115 total time=   0.0s
[CV 4/5] END .........C=1, gamma=10, kernel=rbf;, score=0.051 total time=   0.0s
[CV 5/5] END ........C=1, gamma=10, kernel=rbf;, score=-0.073 total time=   0.0s
[CV 1/5] END .......C=1, gamma=100, kernel=rbf;, score=-0.068 total time=   0.0s
[CV 2/5] END .......C=1, gamma=100, kernel=rbf;, score=-0.059 total time=   0.0s
[CV 3/5] END .......C=1, gamma=100, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 4/5] END ........C=1, gamma=100, kernel=rbf;, score=0.033 total time=   0.0s
[CV 5/5] END .......C=1, gamma=100, kernel=rbf;, score=-0.106 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.144 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.277 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.338 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.342 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.283 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.204 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.474 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.701 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.432 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.592 total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.156 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.433 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.706 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.395 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.541 total time=   0.0s
[CV 1/5] END .......C=10, gamma=10, kernel=rbf;, score=-0.089 total time=   0.0s
[CV 2/5] END ........C=10, gamma=10, kernel=rbf;, score=0.020 total time=   0.0s
[CV 3/5] END ........C=10, gamma=10, kernel=rbf;, score=0.107 total time=   0.0s
[CV 4/5] END ........C=10, gamma=10, kernel=rbf;, score=0.066 total time=   0.0s
[CV 5/5] END ........C=10, gamma=10, kernel=rbf;, score=0.038 total time=   0.0s
[CV 1/5] END ......C=10, gamma=100, kernel=rbf;, score=-0.117 total time=   0.0s
[CV 2/5] END .......C=10, gamma=100, kernel=rbf;, score=0.025 total time=   0.0s
[CV 3/5] END .......C=10, gamma=100, kernel=rbf;, score=0.053 total time=   0.0s
[CV 4/5] END .......C=10, gamma=100, kernel=rbf;, score=0.059 total time=   0.0s
[CV 5/5] END .......C=10, gamma=100, kernel=rbf;, score=0.007 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.215 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.502 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.717 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.420 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.601 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.154 total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.515 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.727 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.368 total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.581 total time=   0.0s
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.147 total time=   0.0s
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.537 total time=   0.0s
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.710 total time=   0.0s
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.499 total time=   0.0s
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.354 total time=   0.0s
[CV 1/5] END ......C=100, gamma=10, kernel=rbf;, score=-0.222 total time=   0.0s
[CV 2/5] END .......C=100, gamma=10, kernel=rbf;, score=0.046 total time=   0.0s
[CV 3/5] END .......C=100, gamma=10, kernel=rbf;, score=0.082 total time=   0.0s
[CV 4/5] END ......C=100, gamma=10, kernel=rbf;, score=-0.308 total time=   0.0s
[CV 5/5] END .......C=100, gamma=10, kernel=rbf;, score=0.061 total time=   0.0s
[CV 1/5] END .....C=100, gamma=100, kernel=rbf;, score=-0.106 total time=   0.0s
[CV 2/5] END ......C=100, gamma=100, kernel=rbf;, score=0.037 total time=   0.0s
[CV 3/5] END ......C=100, gamma=100, kernel=rbf;, score=0.112 total time=   0.0s
[CV 4/5] END ......C=100, gamma=100, kernel=rbf;, score=0.022 total time=   0.0s
[CV 5/5] END ......C=100, gamma=100, kernel=rbf;, score=0.037 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.217 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.518 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.716 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.347 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.635 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.120 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.572 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.752 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.425 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.517 total time=   0.0s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.042 total time=   0.0s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.493 total time=   0.0s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.114 total time=   0.0s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.048 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.284 total time=   0.0s
[CV 1/5] END .....C=1000, gamma=10, kernel=rbf;, score=-0.356 total time=   0.0s
[CV 2/5] END ......C=1000, gamma=10, kernel=rbf;, score=0.035 total time=   0.0s
[CV 3/5] END .....C=1000, gamma=10, kernel=rbf;, score=-0.052 total time=   0.0s
[CV 4/5] END .....C=1000, gamma=10, kernel=rbf;, score=-0.771 total time=   0.0s
[CV 5/5] END ......C=1000, gamma=10, kernel=rbf;, score=0.059 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=100, kernel=rbf;, score=-0.105 total time=   0.0s
[CV 2/5] END .....C=1000, gamma=100, kernel=rbf;, score=0.027 total time=   0.0s
[CV 3/5] END .....C=1000, gamma=100, kernel=rbf;, score=0.106 total time=   0.0s
[CV 4/5] END .....C=1000, gamma=100, kernel=rbf;, score=0.025 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=100, kernel=rbf;, score=0.036 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.215 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.478 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.717 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.442 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.585 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.215 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.478 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.717 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.442 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.585 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.215 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.478 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.717 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.442 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.585 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=10, kernel=linear;, score=0.215 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=10, kernel=linear;, score=0.478 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=10, kernel=linear;, score=0.717 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=10, kernel=linear;, score=0.442 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=10, kernel=linear;, score=0.585 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=100, kernel=linear;, score=0.215 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=100, kernel=linear;, score=0.478 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=100, kernel=linear;, score=0.717 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=100, kernel=linear;, score=0.442 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=100, kernel=linear;, score=0.585 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.227 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.515 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.724 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.366 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.636 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.227 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.515 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.724 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.366 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.636 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.227 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.515 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.724 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.366 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.636 total time=   0.0s
[CV 1/5] END ......C=1, gamma=10, kernel=linear;, score=0.227 total time=   0.0s
[CV 2/5] END ......C=1, gamma=10, kernel=linear;, score=0.515 total time=   0.0s
[CV 3/5] END ......C=1, gamma=10, kernel=linear;, score=0.724 total time=   0.0s
[CV 4/5] END ......C=1, gamma=10, kernel=linear;, score=0.366 total time=   0.0s
[CV 5/5] END ......C=1, gamma=10, kernel=linear;, score=0.636 total time=   0.0s
[CV 1/5] END .....C=1, gamma=100, kernel=linear;, score=0.227 total time=   0.0s
[CV 2/5] END .....C=1, gamma=100, kernel=linear;, score=0.515 total time=   0.0s
[CV 3/5] END .....C=1, gamma=100, kernel=linear;, score=0.724 total time=   0.0s
[CV 4/5] END .....C=1, gamma=100, kernel=linear;, score=0.366 total time=   0.0s
[CV 5/5] END .....C=1, gamma=100, kernel=linear;, score=0.636 total time=   0.0s
[CV 1/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.245 total time=   0.0s
[CV 2/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.527 total time=   0.0s
[CV 3/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.706 total time=   0.0s
[CV 4/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.368 total time=   0.0s
[CV 5/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.651 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.245 total time=   0.0s
[CV 2/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.527 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.706 total time=   0.0s
[CV 4/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.368 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.651 total time=   0.0s
[CV 1/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.245 total time=   0.0s
[CV 2/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.527 total time=   0.0s
[CV 3/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.706 total time=   0.0s
[CV 4/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.368 total time=   0.0s
[CV 5/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.651 total time=   0.0s
[CV 1/5] END .....C=10, gamma=10, kernel=linear;, score=0.245 total time=   0.0s
[CV 2/5] END .....C=10, gamma=10, kernel=linear;, score=0.527 total time=   0.0s
[CV 3/5] END .....C=10, gamma=10, kernel=linear;, score=0.706 total time=   0.0s
[CV 4/5] END .....C=10, gamma=10, kernel=linear;, score=0.368 total time=   0.0s
[CV 5/5] END .....C=10, gamma=10, kernel=linear;, score=0.651 total time=   0.0s
[CV 1/5] END ....C=10, gamma=100, kernel=linear;, score=0.245 total time=   0.0s
[CV 2/5] END ....C=10, gamma=100, kernel=linear;, score=0.527 total time=   0.0s
[CV 3/5] END ....C=10, gamma=100, kernel=linear;, score=0.706 total time=   0.0s
[CV 4/5] END ....C=10, gamma=100, kernel=linear;, score=0.368 total time=   0.0s
[CV 5/5] END ....C=10, gamma=100, kernel=linear;, score=0.651 total time=   0.0s
[CV 1/5] END .C=100, gamma=0.001, kernel=linear;, score=0.247 total time=   0.0s
[CV 2/5] END .C=100, gamma=0.001, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END .C=100, gamma=0.001, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END .C=100, gamma=0.001, kernel=linear;, score=0.373 total time=   0.0s
[CV 5/5] END .C=100, gamma=0.001, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.247 total time=   0.0s
[CV 2/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.373 total time=   0.0s
[CV 5/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.247 total time=   0.0s
[CV 2/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.373 total time=   0.0s
[CV 5/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END ....C=100, gamma=10, kernel=linear;, score=0.247 total time=   0.0s
[CV 2/5] END ....C=100, gamma=10, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END ....C=100, gamma=10, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END ....C=100, gamma=10, kernel=linear;, score=0.373 total time=   0.0s
[CV 5/5] END ....C=100, gamma=10, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END ...C=100, gamma=100, kernel=linear;, score=0.247 total time=   0.0s
[CV 2/5] END ...C=100, gamma=100, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END ...C=100, gamma=100, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END ...C=100, gamma=100, kernel=linear;, score=0.373 total time=   0.0s
[CV 5/5] END ...C=100, gamma=100, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END C=1000, gamma=0.001, kernel=linear;, score=0.246 total time=   0.0s
[CV 2/5] END C=1000, gamma=0.001, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END C=1000, gamma=0.001, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END C=1000, gamma=0.001, kernel=linear;, score=0.374 total time=   0.0s
[CV 5/5] END C=1000, gamma=0.001, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.246 total time=   0.0s
[CV 2/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.374 total time=   0.0s
[CV 5/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.246 total time=   0.0s
[CV 2/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.374 total time=   0.0s
[CV 5/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=10, kernel=linear;, score=0.246 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=10, kernel=linear;, score=0.532 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=10, kernel=linear;, score=0.705 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=10, kernel=linear;, score=0.374 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=10, kernel=linear;, score=0.650 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=100, kernel=linear;, score=0.246 total time=   0.0s

{'C': 100, 'gamma': 0.001, 'kernel': 'linear'}

In [12]:
pred=grid.predict(X_test)
print(r2_score(Y_test,pred))

0.5453618268263478