In [1]:
from sklearn.datasets import load_iris
X,y=load_iris(return_X_y=True)

In [3]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)
X_train

array([[7.7, 2.6, 6.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 2.7, 3.9, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 4.9, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [6.7, 3.3, 5.7, 2.5],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.5, 2.4, 3.7, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [5.4, 3.4, 1.7, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [4.7, 3.2, 1.6, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3.6, 1.4, 0.1],
       [6.9, 3.1, 5.4, 2.1],
       [4.8, 3. , 1.4, 0.3],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [4.4, 3.2, 1.3, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [7.9, 3.8, 6.4, 2. ],
       [6.5, 3. , 5.5, 1.8],
       [7.6, 3. , 6.6, 2.1],
       [6.3, 2.8, 5.1, 1.5],
       [4.6, 3.4, 1.4, 0.3],
       [5.7, 2.6, 3.5, 1. ],
       [6.7, 2.5, 5.8, 1.8],
       [5.7, 2.8, 4.1, 1.3],
       [4.9, 3.1, 1.5, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [7. , 3.2, 4.7, 1.4],
       [5.7, 2.9, 4.2, 1.3],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.1, 3.8, 1.9, 0.4],
       [5.4, 3. , 4.5, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [6.3, 2.9, 5.6, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [5. , 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.5, 3. , 5.8, 2.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.1, 2.8, 4. , 1.3],
       [5.5, 2.4, 3.8, 1.1],
       [6.5, 3.2, 5.1, 2. ],
       [6.5, 3. , 5.2, 2. ],
       [5.9, 3. , 5.1, 1.8],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 2.9, 4.3, 1.3],
       [5.2, 3.4, 1.4, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.3, 1.7, 0.5],
       [4.6, 3.6, 1. , 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 2.3, 3.3, 1. ],
       [5.7, 3.8, 1.7, 0.3],
       [5.2, 3.5, 1.5, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [5.4, 3.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 2.5, 4. , 1.3],
       [6. , 2.2, 5. , 1.5],
       [4.8, 3.1, 1.6, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [6.2, 3.4, 5.4, 2.3],
       [5. , 3. , 1.6, 0.2],
       [6. , 3. , 4.8, 1.8],
       [4.3, 3. , 1.1, 0.1],
       [5.6, 2.5, 3.9, 1.1],
       [6.7, 3. , 5. , 1.7],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 2.2, 4. , 1. ],
       [7.7, 2.8, 6.7, 2. ],
       [7.3, 2.9, 6.3, 1.8],
       [5.6, 3. , 4.1, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 6. , 2.5],
       [5.4, 3.9, 1.3, 0.4],
       [6.4, 3.2, 5.3, 2.3],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.5, 1.4, 0.2],
       [6.1, 2.8, 4.7, 1.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.7, 4.9, 1.8],
       [5.7, 2.5, 5. , 2. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.7, 4.4, 1.5, 0.4],
       [7.2, 3.2, 6. , 1.8],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

[[11  0  0]
 [ 0 15  0]
 [ 0  0 12]]
1.0

In [51]:
import seaborn as sns
ds=sns.load_dataset('tips')

In [52]:
ds.columns=ds.columns.str.strip()

In [53]:
X=ds[['total_bill','tip','smoker','day','time','size']]
y=ds['sex']

In [55]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)
X_train

     total_bill   tip smoker   day    time  size
58        11.24  1.76    Yes   Sat  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
68        20.23  2.01     No   Sat  Dinner     2
184       40.55  3.00    Yes   Sun  Dinner     2
..          ...   ...    ...   ...     ...   ...
64        17.59  2.64     No   Sat  Dinner     3
15        21.58  3.92     No   Sun  Dinner     2
228       13.28  2.72     No   Sat  Dinner     2
125       29.80  4.20     No  Thur   Lunch     6
9         14.78  3.23     No   Sun  Dinner     2

[183 rows x 6 columns]

In [56]:
y_train

58       Male
1        Male
2        Male
68       Male
184      Male
        ...
64       Male
15       Male
228      Male
125    Female
9        Male
Name: sex, Length: 183, dtype: category
Categories (2, str): ['Male', 'Female']

In [57]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
l2=LabelEncoder()
l3=LabelEncoder()
l4=LabelEncoder()
X_train['smoker']=l1.fit_transform(X_train['smoker'])
X_train['day']=l2.fit_transform(X_train['day'])
X_train['time']=l3.fit_transform(X_train['time'])
y_train=l4.fit_transform(y_train)
X_test['smoker']=l1.transform(X_test['smoker'])
X_test['day']=l2.transform(X_test['day'])
X_test['time']=l3.transform(X_test['time'])
y_test=l4.transform(y_test)

In [58]:
X_train

     total_bill   tip  smoker  day  time  size
58        11.24  1.76       1    1     0     2
1         10.34  1.66       0    2     0     3
2         21.01  3.50       0    2     0     3
68        20.23  2.01       0    1     0     2
184       40.55  3.00       1    2     0     2
..          ...   ...     ...  ...   ...   ...
64        17.59  2.64       0    1     0     3
15        21.58  3.92       0    2     0     2
228       13.28  2.72       0    1     0     2
125       29.80  4.20       0    3     1     6
9         14.78  3.23       0    2     0     2

[183 rows x 6 columns]

In [45]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0])

In [59]:
from sklearn.naive_bayes import GaussianNB
gnb1=GaussianNB()
gnb1.fit(X_train,y_train)
y_pred1=gnb1.predict(X_test)
print(classification_report(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.65      0.55      0.59        20
           1       0.80      0.85      0.82        41

    accuracy                           0.75        61
   macro avg       0.72      0.70      0.71        61
weighted avg       0.75      0.75      0.75        61

[[11  9]
 [ 6 35]]
0.7540983606557377