In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('cardekho_imputated.csv')
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [3]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [4]:
df.drop(['car_name','brand','Unnamed: 0'],axis=1,inplace=True)
df

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...
15406,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [5]:
df['model'].unique()

<StringArray>
[        'Alto',        'Grand',          'i20',     'Ecosport',
      'Wagon R',          'i10',        'Venue',        'Swift',
        'Verna',       'Duster',
 ...
     'Panamera',      'Alturas',       'Altroz',           'NX',
     'Carnival',            'C',           'RX',        'Ghost',
 'Quattroporte',       'Gurkha']
Length: 120, dtype: str

In [6]:
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
lb=LabelEncoder()
df['model']=lb.fit_transform(df['model'])
df['model'].value_counts()

model
118    906
89     890
88     781
7      778
25     757
      ...
8        1
15       1
52       1
75       1
55       1
Name: count, Length: 120, dtype: int64

In [7]:
X=df.drop(['selling_price'],axis=1)
y=df['selling_price']
X

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
15406,117,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
15407,42,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
15408,77,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
15409,114,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
15410,25,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [8]:
num_features=X.select_dtypes(exclude='str').columns
cat_features=X.select_dtypes(include='str').columns
print(num_features)
print(cat_features)

Index(['model', 'vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power',
       'seats'],
      dtype='str')
Index(['seller_type', 'fuel_type', 'transmission_type'], dtype='str')

In [9]:
from sklearn.compose import ColumnTransformer
num_trans=StandardScaler()
cat_trans=OneHotEncoder(drop='first')
processers=ColumnTransformer([
        ('OneHotEncoder',cat_trans,cat_features),
        ('StandardScaler',num_trans,num_features)
    ],remainder='passthrough'
)
X=processers.fit_transform(X)
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [11]:
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

def evaluate_score(test,pred):
    mse=mean_squared_error(test,pred)
    mae=mean_absolute_error(test,pred)
    r2=r2_score(test,pred)
    return mse,mae,r2

In [14]:
models={
    'Random Forest':RandomForestRegressor(),
    'KNN':KNeighborsRegressor(),
    "Adaboost":AdaBoostRegressor(),
    'Gradient_boosting':GradientBoostingRegressor()
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    mse_test,mae_test,r2_test=evaluate_score(y_test,y_pred)
    print(list(models.keys())[i])
    print("Mse : ",mse_test)
    print("MAE : ",mae_test)
    print("R2_score : ",r2_test)
    print('\n')

Random Forest
Mse :  234780084858.16248
MAE :  106865.22322165535
R2_score :  0.7855055561751095


KNN
Mse :  307313748829.4835
MAE :  117546.74279781988
R2_score :  0.719238999020106


Adaboost
Mse :  386589000035.76086
MAE :  292983.6181848065
R2_score :  0.6468133461933698


Gradient_boosting
Mse :  239105039262.18536
MAE :  126624.92550003232
R2_score :  0.7815542896525707

In [17]:
from sklearn.model_selection import GridSearchCV
knn_params={
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
    'n_neighbors':[5,6,7,8]
}
random_params={
    'n_estimators':[100,500,1000],
    'max_features':['sqrt', 'log2', None]
}
ada_boost_params={
    'n_estimators':[50,100,250,500,1000],
    'loss':['linear', 'square', 'exponential']
}


gradient_params={
    'n_estimators':[100,500,1000],
    'min_samples_split':[2,4,6,8,10],
    'max_depth':[2,3,4,5],
    'loss':['squared_error', 'absolute_error', 'huber', 'quantile']
}
combo=[
    ('knn',KNeighborsRegressor(),knn_params),
    ('random forest',RandomForestRegressor(),random_params),
    ('Ada Boost',AdaBoostRegressor(),ada_boost_params),
    ('Gradient Boosting',GradientBoostingRegressor(),gradient_params)
]
for name,model,params in combo:
    grid=GridSearchCV(model,param_grid=params,cv=5,verbose=2,refit=True,n_jobs=-1)
    grid.fit(X_train,y_train)
    y_pred=grid.predict(X_test)
    mse,mae,r2=evaluate_score(y_test,y_pred)
    print(name)
    print(mse)
    print(mae)
    print(r2)
    print(grid.best_params_)
    print("\n")

Fitting 5 folds for each of 16 candidates, totalling 80 fits
knn
307208509099.4031
117504.33428497275
0.719335145749866
{'algorithm': 'ball_tree', 'n_neighbors': 5}


Fitting 5 folds for each of 9 candidates, totalling 45 fits
random forest
231234930763.4851
106364.09554713462
0.7887443992663825
{'max_features': None, 'n_estimators': 1000}


Fitting 5 folds for each of 15 candidates, totalling 75 fits
Ada Boost
375185554620.1074
260903.35403172686
0.6572315027571847
{'loss': 'linear', 'n_estimators': 50}


Fitting 5 folds for each of 240 candidates, totalling 1200 fits
Gradient Boosting
263652231277.19556
103718.23872771453
0.7591280421201052
{'loss': 'huber', 'max_depth': 4, 'min_samples_split': 4, 'n_estimators': 1000}